services:
  praha-challenge-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: praha-challenge-db-02
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=employees
    ports:
      - 3306:3306
    volumes:
      - praha-challenge-db-data-02:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d

volumes:
  praha-challenge-db-data-02:
